spring:
  profiles:
    active: file
  application:
    name: springboot-dubbo-seata-order
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.url}:3306/seata_1?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: ${mysql.username}
    password: ${mysql.password}

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: pers.seata.business.dao.domain
  configuration:
    map-underscore-to-camel-case: true

mysql:
  url: 121.40.24.147
  username: root
  password: sunshine

seata:
  application-id: springboot-dubbo-seata-order
  tx-service-group: order_tx_group

dubbo:
  protocol:
    port: 20884
    name: dubbo
  registry:
    address: nacos://121.40.24.147:8848
